const CITY_COORDS = {
  'Gdańsk':[54.352,18.6466],'Kraków':[50.0647,19.945],'Munich':[48.1351,11.582],'Cologne':[50.9375,6.9603],'Luxembourg City':[49.6116,6.1319],'Ghent':[51.0543,3.7174],'Amsterdam':[52.3676,4.9041],'Palma':[39.5696,2.6502],'Madrid':[40.4168,-3.7038],'Córdoba':[37.8882,-4.7794],'Sevilla':[37.3891,-5.9845],'Ronda':[36.7462,-5.1612],'Setenil':[36.8628,-5.1818],'Granada':[37.1773,-3.5986],'València':[39.4699,-0.3763],'Peñíscola':[40.3579,0.4069],'Barcelona':[41.3874,2.1686],'Venice':[45.4408,12.3155],'Vienna':[48.2082,16.3738],'Bratislava':[48.1486,17.1077],'Budapest':[47.4979,19.0402],'Prague':[50.0755,14.4378],'Copenhagen':[55.6761,12.5683],'Tallinn':[59.437,24.7536],'Riga':[56.9496,24.1052],'Vilnius':[54.6872,25.2797],'Frankfurt':[50.1109,8.6821],'Dortmund':[51.5136,7.4653]
};
const priorityOrder={Must:0,Nice:1,'If nearby':2};
let places=[],itinerary=[],visibleCount=18,map,markers={};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const unique=(arr)=>[...new Set(arr.filter(Boolean))];

fetch('data/trip-data.json').then(r=>{if(!r.ok)throw new Error(`Data request failed (${r.status})`);return r.json()}).then(data=>{places=data.places; itinerary=data.itinerary; init();}).catch(()=>{document.querySelector('main').innerHTML='<section class="section"><h1>Could not load trip data.</h1><p>Please refresh the page. If this persists, the published data file may be unavailable.</p></section>';});

function init(){
  document.querySelector('#placeCount').textContent=places.length;
  document.querySelector('#cityCount').textContent=unique(places.map(p=>p.city)).length;
  document.querySelector('#dayCount').textContent=itinerary.length;
  document.querySelector('#mustCount').textContent=places.filter(p=>p.priority==='Must').length;
  fillSelect('cityFilter',unique(places.map(p=>p.city)).sort()); fillSelect('typeFilter',unique(places.map(p=>p.type)).sort()); fillSelect('priorityFilter',['Must','Nice','If nearby']); fillSelect('timeFilter',unique(places.map(p=>p['best time'])).sort()); fillSelect('scheduleCity',unique(itinerary.map(p=>p.city)));
  drawVisuals(); if(window.L){initMap()}else{document.querySelector('#map').innerHTML='<div class="empty">The map is temporarily unavailable, but all trip activities and filters are ready below.</div>'} renderRoute(); renderPlaces(); renderItinerary();
  ['searchInput','cityFilter','typeFilter','priorityFilter','timeFilter','sortSelect'].forEach(id=>document.querySelector('#'+id).addEventListener('input',()=>{visibleCount=18;renderPlaces()}));
  document.querySelector('#clearFilters').onclick=()=>{['searchInput','cityFilter','typeFilter','priorityFilter','timeFilter'].forEach(id=>document.querySelector('#'+id).value='all');document.querySelector('#searchInput').value='';document.querySelector('#sortSelect').value='priority';visibleCount=18;renderPlaces()};
  document.querySelector('#showMore').onclick=()=>{visibleCount+=18;renderPlaces()};
  document.querySelector('#scheduleCity').oninput=renderItinerary; document.querySelector('#todayButton').onclick=()=>{document.querySelector('#scheduleCity').value='all';renderItinerary();document.querySelector('#schedule').scrollIntoView({behavior:'smooth'})};
}
function fillSelect(id,items){const el=document.querySelector('#'+id);items.forEach(x=>el.insertAdjacentHTML('beforeend',`<option value="${esc(x)}">${esc(x)}</option>`));}
function drawVisuals(){
  const types=countBy(places,'type'), topTypes=Object.entries(types).sort((a,b)=>b[1]-a[1]).slice(0,7), max=topTypes[0][1];
  document.querySelector('#typeChart').innerHTML=topTypes.map(([name,count])=>`<div class="bar-row"><span>${esc(name)}</span><div class="bar-track"><div class="bar-fill" style="width:${count/max*100}%"></div></div><span class="bar-count">${count}</span></div>`).join('');
  const cities=Object.entries(countBy(places,'city')).sort((a,b)=>b[1]-a[1]).slice(0,5);document.querySelector('#topCities').innerHTML=cities.map(([city,count])=>`<li>${esc(city)} <b>${count} places</b></li>`).join('');
  const pc=countBy(places,'priority'), colors={Must:'#f05b3b',Nice:'#bddb68','If nearby':'#8e9c94'}, total=places.length; let at=0;const stops=Object.entries(colors).map(([k,color])=>{const pct=(pc[k]||0)/total*100,part=`${color} ${at}% ${at+pct}%`;at+=pct;return part}).join(',');document.querySelector('#priorityChart').style.background=`conic-gradient(${stops})`;document.querySelector('#priorityLegend').innerHTML=Object.entries(colors).map(([k,c])=>`<p><span><i class="priority-key" style="background:${c}"></i>${k}</span><b>${pc[k]||0}</b></p>`).join('');
}
function countBy(arr,key){return arr.reduce((a,x)=>{const k=x[key]||'Other';a[k]=(a[k]||0)+1;return a},{})}
function initMap(){
  map=L.map('map',{scrollWheelZoom:false,zoomControl:false}).setView([49.5,10],4);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'© OpenStreetMap © CARTO',maxZoom:18}).addTo(map);
  const cities=unique(itinerary.map(x=>x.city)).filter(c=>CITY_COORDS[c]); const route=cities.map(c=>CITY_COORDS[c]); L.polyline(route,{color:'#17332e',weight:2,dashArray:'5 7',opacity:.8}).addTo(map);
  cities.forEach((city,index)=>{const count=places.filter(p=>p.city===city).length;const marker=L.marker(CITY_COORDS[city],{icon:L.divIcon({className:'city-marker',iconSize:[13,13]})}).addTo(map).bindPopup(`<strong>${city}</strong><br>${count||'No'} saved places`);marker.on('click',()=>selectCity(city));markers[city]=marker;});
  map.fitBounds(route,{padding:[40,40],maxZoom:5});
}
function renderRoute(){const cities=unique(itinerary.map(x=>x.city));document.querySelector('#routeStrip').innerHTML=cities.map(c=>`<button class="route-city" data-city="${esc(c)}">${esc(c)}</button>`).join('');document.querySelectorAll('.route-city').forEach(btn=>btn.onclick=()=>selectCity(btn.dataset.city));}
function selectCity(city){document.querySelector('#cityFilter').value=city;visibleCount=18;renderPlaces();document.querySelectorAll('.route-city').forEach(x=>x.classList.toggle('active',x.dataset.city===city));if(markers[city]){map.flyTo(CITY_COORDS[city],6);markers[city].openPopup()}document.querySelector('#explore').scrollIntoView({behavior:'smooth'});}
function filteredPlaces(){const q=document.querySelector('#searchInput').value.trim().toLowerCase(), city=document.querySelector('#cityFilter').value,type=document.querySelector('#typeFilter').value,priority=document.querySelector('#priorityFilter').value,time=document.querySelector('#timeFilter').value,sort=document.querySelector('#sortSelect').value;let result=places.filter(p=>{const hay=Object.values(p).join(' ').toLowerCase();return(!q||hay.includes(q))&&(city==='all'||p.city===city)&&(type==='all'||p.type===type)&&(priority==='all'||p.priority===priority)&&(time==='all'||p['best time']===time)});return result.sort((a,b)=>sort==='priority'?(priorityOrder[a.priority]??9)-(priorityOrder[b.priority]??9)||a.city.localeCompare(b.city):String(a[sort]||'').localeCompare(String(b[sort]||'')));}
function renderPlaces(){const result=filteredPlaces(), slice=result.slice(0,visibleCount);document.querySelector('#resultCount').textContent=`${result.length} ${result.length===1?'place':'places'} found`;document.querySelector('#placeGrid').innerHTML=slice.length?slice.map(placeCard).join(''):'<div class="empty">Nothing matches those filters. Try widening the search.</div>';const btn=document.querySelector('#showMore');btn.style.display=result.length>visibleCount?'block':'none';}
function placeCard(p){const priority=p.priority||'Nice',maps=p['maps link'];return `<article class="place-card"><div class="place-top"><span class="tag">${esc(p.type)}</span><span class="priority ${priority==='Must'?'must':''}">${esc(priority)}</span></div><h3>${esc(p.name)}</h3><p class="place-city">${esc(p.city)} · ${esc(p.neighbourhood||'City centre')}</p><p class="why">${esc(p['why it made the list']||p.notes||'Saved for this trip.')}</p><div class="place-bottom"><span>${esc(p['best time']||'Flexible')} · ${esc(p['approx cost']||'Price TBC')}</span>${maps?`<a href="${esc(maps)}" target="_blank" rel="noopener">Open map ↗</a>`:''}</div></article>`}
function renderItinerary(){const city=document.querySelector('#scheduleCity').value,rows=itinerary.filter(x=>city==='all'||x.city===city);document.querySelector('#itineraryList').innerHTML=rows.map(x=>{const date=new Date(x.date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'}),heavy=(x.notes||'').startsWith('HEAVY DAY.');return `<article class="day-row"><time class="day-date">${date}</time><div class="day-city">${esc(x.city)}<small>${esc(x.country||'')}</small></div><div class="day-notes">${heavy?'<b>HEAVY DAY</b> ':''}${esc((x.notes||'').replace('HEAVY DAY. ',''))}</div></article>`}).join('');}
