/* Europa Trip Atlas
 * ---------------------------------------------------------------------------
 * Reads data/trip-data.json, which is generated by scripts/extract_trip_data.py
 * from Europe_2026_Master_Trip_File.md. Do not hand-edit the JSON.
 */

'use strict';

/* --------------------------------------------------------------------------
 * Tile provider
 *
 * Default is the OpenStreetMap standard layer: no API key, no watermark.
 * The previous build used CARTO's raster basemaps without a key, and CARTO
 * now stamps "API KEY REQUIRED" diagonally across every one of those tiles.
 *
 * OSM's tile usage policy forbids prefetching or bulk-downloading tiles for
 * offline use, so sw.js deliberately does NOT cache map tiles. If you want an
 * offline map, get a CARTO key (or self-host) and switch TILES below --- then
 * you may also enable tile caching in sw.js.
 *   https://operations.osmfoundation.org/policies/tiles/
 * ------------------------------------------------------------------------ */
const TILES = {
  url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
  options: {
    maxZoom: 19,
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  },
};

// Swap to this once you hold a CARTO key. Attribution string is CARTO's own.
// const TILES = {
//   url: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png?key=YOUR_KEY',
//   options: {
//     subdomains: 'abcd',
//     maxZoom: 20,
//     attribution:
//       '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, ' +
//       '&copy; <a href="https://carto.com/attributions">CARTO</a>',
//   },
// };

const PAGE_SIZE = 18;
const PRIORITY_ORDER = { Must: 0, Nice: 1, 'If nearby': 2 };
const PRIORITY_COLOURS = { Must: '#f05b3b', Nice: '#8aa84a', 'If nearby': '#6f7d75' };
const FALLBACK_COLOUR = '#b9b1a2';

// Only these fields are searched. The old build searched Object.values(place),
// which included the Google Maps URL, so "com", "maps" or "https" matched
// every single row.
const SEARCH_FIELDS = [
  'name', 'city', 'neighbourhood', 'type',
  'why it made the list', 'notes', 'address or coordinates',
];

// data/my-places.json is hand-maintained and may legitimately not exist. If
// the request stalls rather than 404s, the page must still render, so the load
// is raced against this deadline and then given up on.
const PERSONAL_TIMEOUT_MS = 4000;

const state = {
  meta: {},
  cities: {},
  route: [],
  // The 406 tracker places, exactly as generated. Never has personal places
  // mixed in: renderStats and drawVisuals describe the tracker data, and the
  // hero count must stay at meta.places. Issue 4 of the original audit was the
  // hero being overwritten with a different number at runtime.
  places: [],
  // Personal additions from data/my-places.json. Counted separately.
  personal: [],
  itinerary: [],
  visibleCount: PAGE_SIZE,
  heavyOnly: false,
  map: null,
  markers: {},
};

// The working list for search, filters and the place grid. Tracker places
// first, so the default ordering is unchanged when there are no personal ones.
const allPlaces = () => state.places.concat(state.personal);

const $ = (sel) => document.querySelector(sel);
const esc = (s) =>
  String(s ?? '').replace(/[&<>'"]/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;',
  })[c]);
const unique = (arr) => [...new Set(arr.filter(Boolean))];

/* ---------------------------------------------------------------- boot ---- */

fetch('data/trip-data.json?v=3')
  .then((r) => {
    if (!r.ok) throw new Error(`Data request failed (HTTP ${r.status})`);
    return r.json();
  })
  .then((data) => {
    Object.assign(state, {
      meta: data.meta || {},
      cities: data.cities || {},
      route: data.route || [],
      places: data.places || [],
      itinerary: data.itinerary || [],
    });
    return loadPersonalPlaces();
  })
  .then((personal) => {
    state.personal = personal;
    init();
  })
  .catch((err) => {
    // The old build swallowed this with a bare .catch(() => ...), which made
    // every field failure undiagnosable.
    console.error('Trip data could not be loaded:', err);
    showFatal(err);
  });

/* Personal places. A missing file, a malformed file, a wrong version or a
 * stalled request all yield an empty list and ONE console warning. None of
 * them may break the page: the file is optional by design, and the 406
 * tracker places must render whether or not it exists. */
function loadPersonalPlaces() {
  const request = fetch('data/my-places.json?v=3')
    .then((r) => {
      // 404 is the normal state before the first personal place is added, but
      // it is still reported once, so a file that fails to publish is visible
      // rather than looking like "no personal places yet".
      if (r.status === 404) {
        throw new Error('data/my-places.json is not published (HTTP 404)');
      }
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return r.json();
    })
    .then((doc) => {
      if (doc.version !== 1) {
        throw new Error(`unexpected version ${JSON.stringify(doc.version)}`);
      }
      if (!Array.isArray(doc.places)) throw new Error('"places" is not an array');
      return doc.places
        .filter((p) => p && typeof p === 'object' && p.name)
        // origin is forced here rather than trusted from the file, so a row
        // can never render without its MY PICK marking.
        .map((p) => Object.assign({}, p, { origin: 'personal' }));
    })
    .catch((err) => {
      console.warn(
        'Personal places could not be loaded; continuing with tracker places only:',
        err
      );
      return [];
    });

  const deadline = new Promise((resolve) => {
    setTimeout(() => resolve(null), PERSONAL_TIMEOUT_MS);
  });

  return Promise.race([request, deadline]).then((rows) => rows || []);
}

function showFatal(err) {
  const main = $('main');
  if (!main) return;
  main.innerHTML =
    '<section class="section"><h1>Could not load the trip data.</h1>' +
    '<p>Try refreshing. If it keeps happening, check that ' +
    '<code>data/trip-data.json</code> is published alongside this page.</p>' +
    `<p class="fatal-detail">${esc(err && err.message ? err.message : String(err))}</p>` +
    '</section>';
}

/* Each render step is isolated. The old build ran them as one chain of
 * statements, so a throw inside the map killed Explore and Schedule too. */
function step(label, fn) {
  try {
    fn();
  } catch (err) {
    console.error(`Render step "${label}" failed:`, err);
  }
}

function init() {
  step('stats', renderStats);
  step('filters', fillFilters);
  step('charts', drawVisuals);
  step('map', initMap);
  step('routeStrip', renderRoute);
  step('places', renderPlaces);
  step('itinerary', renderItinerary);
  step('listeners', bindListeners);
}

/* --------------------------------------------------------------- stats ---- */

function renderStats() {
  const m = state.meta;
  $('#placeCount').textContent = m.places ?? state.places.length;
  $('#cityCount').textContent = m.cities ?? unique(state.places.map((p) => p.city)).length;
  $('#dayCount').textContent = m.days ?? state.itinerary.length;
  $('#mustCount').textContent =
    m.musts ?? state.places.filter((p) => p.priority === 'Must').length;
  $('#statGrid').setAttribute('aria-busy', 'false');

  // Personal places are reported alongside the tracker total, never added to
  // it. meta is not mutated: the four figures above stay 406 / 27 / 76 / 149
  // whatever is in data/my-places.json.
  const note = $('#personalNote');
  if (note) {
    const n = state.personal.length;
    if (n) {
      note.textContent = `Plus ${n} personal pick${n === 1 ? '' : 's'} you added.`;
      note.hidden = false;
    } else {
      note.textContent = '';
      note.hidden = true;
    }
  }

  if (m.generatedAt) {
    $('#dataStamp').textContent = `Data generated ${m.generatedAt.replace('T', ' ').replace('+00:00', ' UTC')}.`;
  }
  renderNextStop();
}

function renderNextStop() {
  const today = startOfDay(new Date());
  const rows = state.itinerary.filter((r) => parseDate(r.date));
  if (!rows.length) return;

  const first = parseDate(rows[0].date);
  const last = parseDate(rows[rows.length - 1].date);
  let label = 'Next stop';
  let row = null;

  if (today < first) {
    label = 'First stop';
    row = rows[0];
  } else if (today > last) {
    label = 'Trip complete';
    row = rows[rows.length - 1];
  } else {
    label = 'Today';
    row = rows.find((r) => sameDay(parseDate(r.date), today)) || rows[0];
  }

  $('#nextStopLabel').textContent = label;
  const city = row.baseCity || row.base;
  $('#nextStopCity').textContent = row.country ? `${city}, ${row.country}` : city;

  const d = parseDate(row.date);
  $('#nextStopDate').innerHTML = d
    ? `${d.toLocaleDateString('en-GB', { month: 'short' }).toUpperCase()}<br />${d.getDate()}`
    : '—';
}

/* ------------------------------------------------------------- filters ---- */

function fillFilters() {
  // Built from the merged list, so a personal place with a type or city that
  // no tracker place uses is still reachable from the filters.
  const all = allPlaces();
  fillSelect('cityFilter', unique(all.map((p) => p.city)).sort());
  fillSelect('typeFilter', unique(all.map((p) => p.type)).sort());
  fillSelect('priorityFilter', ['Must', 'Nice', 'If nearby']);
  fillSelect('timeFilter', unique(all.map((p) => p.timeBucket)).sort());
  fillSelect('costFilter', unique(all.map((p) => p.costTier)).sort());
  // The schedule is tracker-only: personal places never enter the itinerary.
  fillSelect('scheduleCity', unique(state.itinerary.map((r) => r.baseCity)));
}

function fillSelect(id, items) {
  const el = $('#' + id);
  if (!el) return;
  items.forEach((x) => {
    el.insertAdjacentHTML('beforeend', `<option value="${esc(x)}">${esc(x)}</option>`);
  });
}

/* -------------------------------------------------------------- charts ---- */

function drawVisuals() {
  const places = state.places;
  const typeChart = $('#typeChart');
  const topCities = $('#topCities');
  const legend = $('#priorityLegend');
  const donut = $('#priorityChart');

  // The old build read topTypes[0][1] unguarded and threw on empty data,
  // which killed every render step after it.
  if (!places.length) {
    typeChart.innerHTML = '<p class="empty">No places to chart.</p>';
    topCities.innerHTML = '';
    legend.innerHTML = '';
    return;
  }

  const types = Object.entries(countBy(places, 'type')).sort((a, b) => b[1] - a[1]).slice(0, 8);
  const max = types[0][1] || 1;
  typeChart.innerHTML = types
    .map(
      ([name, count]) =>
        `<div class="bar-row"><span>${esc(name)}</span>` +
        `<div class="bar-track"><div class="bar-fill" style="width:${(count / max) * 100}%"></div></div>` +
        `<span class="bar-count">${count}</span></div>`
    )
    .join('');

  const cities = Object.entries(countBy(places, 'city')).sort((a, b) => b[1] - a[1]).slice(0, 5);
  topCities.innerHTML = cities
    .map(([city, count]) => `<li>${esc(city)} <b>${count} places</b></li>`)
    .join('');

  // Build the donut from whatever priorities actually exist, so an unexpected
  // value shows up as a grey wedge instead of silently leaving a gap.
  const counts = countBy(places, 'priority');
  const total = places.length;
  const keys = Object.keys(counts).sort(
    (a, b) => (PRIORITY_ORDER[a] ?? 9) - (PRIORITY_ORDER[b] ?? 9)
  );
  let at = 0;
  const stops = keys.map((k) => {
    const pct = (counts[k] / total) * 100;
    const part = `${PRIORITY_COLOURS[k] || FALLBACK_COLOUR} ${at}% ${at + pct}%`;
    at += pct;
    return part;
  });
  donut.style.background = `conic-gradient(${stops.join(',')})`;
  donut.setAttribute(
    'aria-label',
    'Priority split: ' + keys.map((k) => `${counts[k]} ${k}`).join(', ')
  );
  legend.innerHTML = keys
    .map(
      (k) =>
        `<p><span><i class="priority-key" style="background:${PRIORITY_COLOURS[k] || FALLBACK_COLOUR}"></i>${esc(k)}</span><b>${counts[k]}</b></p>`
    )
    .join('');
}

function countBy(arr, key) {
  return arr.reduce((acc, x) => {
    const k = x[key] || 'Other';
    acc[k] = (acc[k] || 0) + 1;
    return acc;
  }, {});
}

/* ----------------------------------------------------------------- map ---- */

function initMap() {
  const el = $('#map');
  if (!window.L) {
    el.innerHTML =
      '<p class="empty">The map library did not load. Everything else on this page still works.</p>';
    return;
  }

  const legs = state.route.filter((r) => Number.isFinite(r.lat) && Number.isFinite(r.lon));
  if (!legs.length) {
    el.innerHTML = '<p class="empty">No mappable stops in the trip data.</p>';
    return;
  }

  const map = L.map('map', { scrollWheelZoom: false, zoomControl: false }).setView([49.5, 10], 4);
  state.map = map;
  L.control.zoom({ position: 'bottomright' }).addTo(map);
  L.tileLayer(TILES.url, TILES.options).addTo(map);

  // Ordered legs, not a globally de-duplicated set. This is what makes both
  // Cologne blocks appear; the old code drew Cologne once and skipped the
  // Prague -> Cologne -> Copenhagen leg entirely.
  const line = legs.map((r) => [r.lat, r.lon]);
  L.polyline(line, { color: '#17332e', weight: 2, dashArray: '5 7', opacity: 0.8 }).addTo(map);

  const seen = new Set();
  legs.forEach((leg) => {
    const count = state.places.filter((p) => p.city === leg.city).length;
    const mine = state.personal.filter((p) => p.city === leg.city).length;
    const nights = state.route
      .filter((r) => r.city === leg.city)
      .reduce((sum, r) => sum + r.nights, 0);
    const visits = state.route.filter((r) => r.city === leg.city).length;
    const marker = L.marker([leg.lat, leg.lon], {
      icon: L.divIcon({ className: 'city-marker', iconSize: [13, 13] }),
      title: leg.city,
    })
      .addTo(map)
      .bindPopup(
        `<strong>${esc(leg.city)}</strong><br>${nights} night${nights === 1 ? '' : 's'}` +
          (visits > 1 ? ` across ${visits} stays` : '') +
          `<br>${count || 'No'} saved place${count === 1 ? '' : 's'}` +
          (mine ? ` <br>★ ${mine} of your own` : '')
      );
    marker.on('click', () => selectCity(leg.city));
    if (!seen.has(leg.city)) {
      state.markers[leg.city] = marker;
      seen.add(leg.city);
    }
  });

  // Day stops: passed through, never slept in. The old build had places for
  // Córdoba, Setenil and Peñíscola but no way to see them on the map.
  const dayStops = [];
  state.itinerary.forEach((r) => (r.stops || []).forEach((s) => dayStops.push(s)));
  dayStops.forEach((s) => {
    L.marker([s.lat, s.lon], {
      icon: L.divIcon({ className: 'stop-marker', iconSize: [10, 10] }),
      title: s.name,
    })
      .addTo(map)
      .bindPopup(`<strong>${esc(s.name)}</strong><br>Day stop, no overnight`)
      .on('click', () => selectCity(s.name));
  });

  // Branch A spur to Dortmund for the Champions League match.
  state.itinerary
    .filter((r) => r.kind === 'branch')
    .forEach((r) => {
      const a = (r.branches || []).find((b) => b.id === 'A');
      const b = (r.branches || []).find((x) => x.id === 'B');
      if (!a || !b) return;
      L.polyline([[b.lat, b.lon], [a.lat, a.lon]], {
        color: '#b03214', weight: 2, dashArray: '2 6', opacity: 0.9,
      }).addTo(map);
      L.marker([a.lat, a.lon], {
        icon: L.divIcon({ className: 'branch-marker', iconSize: [11, 11] }),
        title: a.city + ' (branch A)',
      })
        .addTo(map)
        .bindPopup(`<strong>${esc(a.city)}</strong><br>Branch A only, 9 Dec`);
    });

  // fitBounds throws "Bounds are not valid." on an empty array.
  if (line.length) map.fitBounds(line, { padding: [40, 40], maxZoom: 6 });

  const legend = $('#routeLegend');
  if (legend) {
    legend.textContent =
      `${legs.length} legs · ${unique(legs.map((l) => l.city)).length} cities · ` +
      `${dayStops.length} day stops · dashed red line is the 9 Dec branch A spur to Dortmund`;
  }
}

/* --------------------------------------------------------- route strip ---- */

function renderRoute() {
  const cities = unique(state.route.map((r) => r.city));
  $('#routeStrip').innerHTML = cities
    .map(
      (c) =>
        `<button class="route-city" type="button" aria-pressed="false" data-city="${esc(c)}">${esc(c)}</button>`
    )
    .join('');
  document.querySelectorAll('.route-city').forEach((btn) => {
    btn.addEventListener('click', () => selectCity(btn.dataset.city));
  });
}

function selectCity(city) {
  const filter = $('#cityFilter');
  if ([...filter.options].some((o) => o.value === city)) filter.value = city;
  state.visibleCount = PAGE_SIZE;
  renderPlaces();

  document.querySelectorAll('.route-city').forEach((btn) => {
    const on = btn.dataset.city === city;
    btn.classList.toggle('active', on);
    btn.setAttribute('aria-pressed', String(on));
  });

  const marker = state.markers[city];
  if (state.map && marker) {
    state.map.flyTo(marker.getLatLng(), 6);
    marker.openPopup();
  }
  $('#explore').scrollIntoView({ behavior: 'smooth' });
}

/* -------------------------------------------------------------- places ---- */

function filteredPlaces() {
  const q = $('#searchInput').value.trim().toLowerCase();
  const city = $('#cityFilter').value;
  const type = $('#typeFilter').value;
  const priority = $('#priorityFilter').value;
  const time = $('#timeFilter').value;
  const cost = $('#costFilter').value;
  const sort = $('#sortSelect').value;
  const originEl = $('#originFilter');
  const origin = originEl ? originEl.value : 'all';

  const result = allPlaces().filter((p) => {
    if (q) {
      // SEARCH_FIELDS still excludes the maps link, which is what made "com"
      // and "https" match every row in the original build.
      const hay = SEARCH_FIELDS.map((f) => p[f] || '').join(' ').toLowerCase();
      if (!hay.includes(q)) return false;
    }
    if (origin === 'personal' && p.origin !== 'personal') return false;
    if (origin === 'tracker' && p.origin === 'personal') return false;
    if (city !== 'all' && p.city !== city) return false;
    if (type !== 'all' && p.type !== type) return false;
    if (priority !== 'all' && p.priority !== priority) return false;
    if (time !== 'all' && p.timeBucket !== time) return false;
    if (cost !== 'all' && p.costTier !== cost) return false;
    return true;
  });

  return result.sort((a, b) => {
    if (sort === 'priority') {
      return (
        (PRIORITY_ORDER[a.priority] ?? 9) - (PRIORITY_ORDER[b.priority] ?? 9) ||
        a.city.localeCompare(b.city) ||
        a.name.localeCompare(b.name)
      );
    }
    return String(a[sort] || '').localeCompare(String(b[sort] || ''));
  });
}

function renderPlaces() {
  const result = filteredPlaces();
  const slice = result.slice(0, state.visibleCount);

  $('#resultCount').textContent =
    `${result.length} ${result.length === 1 ? 'place' : 'places'} found` +
    (result.length > slice.length ? ` · showing ${slice.length}` : '');

  $('#placeGrid').innerHTML = slice.length
    ? slice.map(placeCard).join('')
    : '<p class="empty">Nothing matches those filters. Try widening the search.</p>';

  $('#showMore').style.display = result.length > state.visibleCount ? 'block' : 'none';
}

function placeCard(p) {
  const priority = p.priority || 'Nice';
  const maps = p['maps link'];
  const hours = p['opening hours'];
  const confidence = p.confidence;

  // Fields the old build dropped entirely: opening hours, notes, confidence,
  // source and date, address. They are the ones that answer "is it open".
  const mine = p.origin === 'personal';

  const meta = [];
  if (hours) meta.push(`<span class="meta-hours"><b>Hours</b> ${esc(hours)}</span>`);
  if (p.notes) meta.push(`<span class="meta-note"><b>Note</b> ${esc(p.notes)}</span>`);
  // Never present an inferred position as an exact one.
  if (mine && p.coordPrecision === 'approx') {
    meta.push(
      '<span class="meta-approx"><b>Location</b> approximate, city centre ' +
      'until a map link or coordinates are added</span>'
    );
  }

  return (
    `<article class="place-card${mine ? ' is-mine' : ''}">` +
    '<div class="place-top"><span class="tag">' +
    // Glyph plus colour, not colour alone, matching the HEAVY DAY treatment.
    (mine ? '<span class="mine-chip">★ MY PICK</span> ' : '') +
    `${esc(p.type)}</span>` +
    `<span class="priority ${priority === 'Must' ? 'must' : ''}">${esc(priority)}</span></div>` +
    `<h3>${esc(p.name)}</h3>` +
    `<p class="place-city">${esc(p.city)} · ${esc(p.neighbourhood || 'City centre')}</p>` +
    `<p class="why">${esc(p['why it made the list'] || 'Saved for this trip.')}</p>` +
    (meta.length ? `<div class="place-meta">${meta.join('')}</div>` : '') +
    '<div class="place-bottom">' +
    `<span>${esc(p['best time'] || 'Flexible')} · ${esc(p['approx cost'] || 'Price TBC')}` +
    (confidence && confidence !== 'Verified'
      ? ` · <em class="confidence">${esc(confidence)}</em>`
      : '') +
    '</span>' +
    (maps
      ? `<a href="${esc(maps)}" target="_blank" rel="noopener noreferrer">Open map <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a>`
      : '') +
    '</div></article>'
  );
}

/* ----------------------------------------------------------- itinerary ---- */

function renderItinerary() {
  const city = $('#scheduleCity').value;
  const rows = state.itinerary.filter((r) => {
    if (city !== 'all' && r.baseCity !== city) return false;
    if (state.heavyOnly && !r.heavy) return false;
    return true;
  });

  const heavyTotal = state.itinerary.filter((r) => r.heavy).length;
  $('#scheduleStatus').textContent =
    `Showing ${rows.length} of ${state.itinerary.length} days` +
    (state.heavyOnly ? ` · ${heavyTotal} heavy days in the whole trip` : '');

  $('#itineraryList').innerHTML = rows.length
    ? rows.map(dayRow).join('')
    : '<p class="empty">No days match.</p>';
}

function dayRow(r) {
  const d = parseDate(r.date);
  const dateLabel = d
    ? d.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' })
    : esc(r.date || 'Undated');

  const today = startOfDay(new Date());
  const isToday = d && sameDay(d, today);

  const cityLabel = r.baseCity || r.base;
  const stops = (r.stops || []).map((s) => s.name);

  const branchHtml = (r.branches || [])
    .map(
      (b) =>
        `<p class="branch"><b>Branch ${esc(b.id)} — ${esc(b.city)}</b> ${esc(b.notes)}</p>`
    )
    .join('');

  return (
    `<article class="day-row${r.heavy ? ' is-heavy' : ''}${isToday ? ' is-today' : ''}" id="day-${esc(r.date)}">` +
    `<time class="day-date" datetime="${esc(r.date)}">${esc(dateLabel)}</time>` +
    `<div class="day-city">${esc(cityLabel)}<small>${esc(r.country || kindLabel(r.kind))}</small>` +
    (stops.length ? `<small class="via">via ${esc(stops.join(', '))}</small>` : '') +
    '</div>' +
    '<div class="day-notes">' +
    (r.heavy ? '<span class="heavy-flag">◆ HEAVY DAY</span> ' : '') +
    (isToday ? '<span class="today-flag">TODAY</span> ' : '') +
    esc(r.notes || '') +
    branchHtml +
    '</div></article>'
  );
}

function kindLabel(kind) {
  if (kind === 'transit') return 'Overnight train';
  if (kind === 'branch') return 'Branch decision';
  if (kind === 'depart') return 'Departure';
  return '';
}

/* ----------------------------------------------------------- listeners ---- */

function bindListeners() {
  const filterIds = [
    'searchInput', 'cityFilter', 'typeFilter',
    'priorityFilter', 'timeFilter', 'costFilter', 'originFilter', 'sortSelect',
  ];
  filterIds.forEach((id) => {
    const el = $('#' + id);
    if (!el) return;
    el.addEventListener('input', () => {
      state.visibleCount = PAGE_SIZE;
      renderPlaces();
    });
  });

  $('#clearFilters').addEventListener('click', () => {
    [
      'cityFilter', 'typeFilter', 'priorityFilter',
      'timeFilter', 'costFilter', 'originFilter',
    ].forEach((id) => {
      const el = $('#' + id);
      if (el) el.value = 'all';
    });
    $('#searchInput').value = '';
    $('#sortSelect').value = 'priority';
    // The old reset left the route strip highlighted and never touched the
    // schedule filter.
    document.querySelectorAll('.route-city').forEach((btn) => {
      btn.classList.remove('active');
      btn.setAttribute('aria-pressed', 'false');
    });
    state.visibleCount = PAGE_SIZE;
    renderPlaces();
  });

  $('#showMore').addEventListener('click', () => {
    state.visibleCount += PAGE_SIZE;
    renderPlaces();
  });

  $('#scheduleCity').addEventListener('input', renderItinerary);

  $('#heavyToggle').addEventListener('click', (e) => {
    state.heavyOnly = !state.heavyOnly;
    e.currentTarget.setAttribute('aria-pressed', String(state.heavyOnly));
    e.currentTarget.classList.toggle('active', state.heavyOnly);
    renderItinerary();
  });

  // A real "today" control. The old button was called todayButton, labelled
  // "Back to start", and did nothing date-aware.
  $('#todayButton').addEventListener('click', () => {
    $('#scheduleCity').value = 'all';
    state.heavyOnly = false;
    $('#heavyToggle').setAttribute('aria-pressed', 'false');
    $('#heavyToggle').classList.remove('active');
    renderItinerary();

    const today = startOfDay(new Date());
    const match = state.itinerary.find((r) => {
      const d = parseDate(r.date);
      return d && d >= today;
    });
    const target = match ? document.getElementById('day-' + match.date) : null;
    (target || $('#schedule')).scrollIntoView({ behavior: 'smooth', block: 'center' });
  });

  const navToggle = $('#navToggle');
  const mobileNav = $('#mobileNav');
  navToggle.addEventListener('click', () => {
    const open = navToggle.getAttribute('aria-expanded') === 'true';
    navToggle.setAttribute('aria-expanded', String(!open));
    mobileNav.hidden = open;
  });
  mobileNav.addEventListener('click', (e) => {
    if (e.target.tagName === 'A') {
      navToggle.setAttribute('aria-expanded', 'false');
      mobileNav.hidden = true;
    }
  });
}

/* ------------------------------------------------------------- helpers ---- */

// Midday avoids the timezone off-by-one. The old build did this too but never
// checked the result, so a bad date rendered the literal text "Invalid Date".
function parseDate(iso) {
  if (!iso || typeof iso !== 'string') return null;
  const d = new Date(iso + 'T12:00:00');
  return Number.isNaN(d.getTime()) ? null : d;
}

function startOfDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate(), 12, 0, 0);
}

function sameDay(a, b) {
  return (
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate()
  );
}

/* ------------------------------------------------------- offline shell ---- */

if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('sw.js')
      .catch((err) => console.warn('Service worker registration failed:', err));
  });
}
