/* Europa Trip Atlas
 * ---------------------------------------------------------------------------
 * Reads data/trip-data.json, which is generated by scripts/extract_trip_data.py
 * from Europe_2026_Master_Trip_File.md. Do not hand-edit the JSON.
 */

'use strict';

/* --------------------------------------------------------------------------
 * Tile provider
 *
 * Default is the OpenStreetMap standard layer: no API key, no watermark.
 * The previous build used CARTO's raster basemaps without a key, and CARTO
 * now stamps "API KEY REQUIRED" diagonally across every one of those tiles.
 *
 * OSM's tile usage policy forbids prefetching or bulk-downloading tiles for
 * offline use, so sw.js deliberately does NOT cache map tiles. If you want an
 * offline map, get a CARTO key (or self-host) and switch TILES below --- then
 * you may also enable tile caching in sw.js.
 *   https://operations.osmfoundation.org/policies/tiles/
 * ------------------------------------------------------------------------ */
const TILES = {
  url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
  options: {
    maxZoom: 19,
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  },
};

// Swap to this once you hold a CARTO key. Attribution string is CARTO's own.
// const TILES = {
//   url: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png?key=YOUR_KEY',
//   options: {
//     subdomains: 'abcd',
//     maxZoom: 20,
//     attribution:
//       '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, ' +
//       '&copy; <a href="https://carto.com/attributions">CARTO</a>',
//   },
// };

const PAGE_SIZE = 18;
const PRIORITY_ORDER = { Must: 0, Nice: 1, 'If nearby': 2 };
const PRIORITY_COLOURS = { Must: '#f05b3b', Nice: '#8aa84a', 'If nearby': '#6f7d75' };
const FALLBACK_COLOUR = '#b9b1a2';

// Only these fields are searched. The old build searched Object.values(place),
// which included the Google Maps URL, so "com", "maps" or "https" matched
// every single row.
const SEARCH_FIELDS = [
  'name', 'city', 'neighbourhood', 'type',
  'why it made the list', 'notes', 'address or coordinates',
];

// data/my-places.json is hand-maintained and may legitimately not exist. If
// the request stalls rather than 404s, the page must still render, so the load
// is raced against this deadline and then given up on.
const PERSONAL_TIMEOUT_MS = 4000;

const state = {
  meta: {},
  cities: {},
  route: [],
  // The 406 tracker places, exactly as generated. Never has personal places
  // mixed in: renderStats and drawVisuals describe the tracker data, and the
  // hero count must stay at meta.places. Issue 4 of the original audit was the
  // hero being overwritten with a different number at runtime.
  places: [],
  // Personal additions from data/my-places.json. Counted separately.
  personal: [],
  itinerary: [],
  visibleCount: PAGE_SIZE,
  heavyOnly: false,
  map: null,
  markers: {},
  // The city view at #city/<slug>. Its Leaflet instance is separate from the
  // route map and is torn down when the view closes, so the two never share
  // a container or a zoom level.
  cityMap: null,
  cityName: null,
};

// The working list for search, filters and the place grid. Tracker places
// first, so the default ordering is unchanged when there are no personal ones.
const allPlaces = () => state.places.concat(state.personal);

const $ = (sel) => document.querySelector(sel);
const esc = (s) =>
  String(s ?? '').replace(/[&<>'"]/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;',
  })[c]);
const unique = (arr) => [...new Set(arr.filter(Boolean))];

/* ---------------------------------------------------------------- boot ---- */

/* A passphrase curtain. Read the comment above #gate in index.html before
 * relying on this for anything: the passphrase is sitting in this file, which
 * is public, and data/trip-data.json can be fetched directly without ever
 * loading index.html. It raises the bar on idle browsing and nothing else.
 *
 * The boot is gated rather than the display, so the trip data is not requested
 * at all until the passphrase is entered. sessionStorage, not localStorage, so
 * closing the tab re-locks it.
 */
const PASSPHRASE = '123';
const UNLOCK_KEY = 'europa-unlocked';

function unlocked() {
  try {
    return sessionStorage.getItem(UNLOCK_KEY) === '1';
  } catch (err) {
    // Private browsing can throw on storage access. Fall back to asking every
    // time rather than failing open or failing to load.
    return false;
  }
}

function showGate() {
  const gate = document.getElementById('gate');
  const form = document.getElementById('gateForm');
  const input = document.getElementById('gateInput');
  const error = document.getElementById('gateError');
  if (!gate || !form || !input) {
    // No gate markup means an older cached index.html. Load rather than lock
    // the owner out of their own trip plan on the day they need it.
    console.warn('Passphrase gate markup missing; continuing without it.');
    boot();
    return;
  }

  document.body.classList.add('gate-open');
  gate.hidden = false;
  input.focus();

  form.addEventListener('submit', (e) => {
    e.preventDefault();
    if (input.value !== PASSPHRASE) {
      if (error) error.hidden = false;
      input.value = '';
      input.focus();
      return;
    }
    try {
      sessionStorage.setItem(UNLOCK_KEY, '1');
    } catch (err) {
      // Not fatal: this session still opens, the next one asks again.
    }
    document.body.classList.remove('gate-open');
    gate.hidden = true;
    boot();
  });
}

if (unlocked()) boot();
else if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', showGate);
} else {
  showGate();
}

function boot() {
  return fetch('data/trip-data.json?v=5')
  .then((r) => {
    if (!r.ok) throw new Error(`Data request failed (HTTP ${r.status})`);
    return r.json();
  })
  .then((data) => {
    Object.assign(state, {
      meta: data.meta || {},
      cities: data.cities || {},
      route: data.route || [],
      places: data.places || [],
      itinerary: data.itinerary || [],
    });
    return loadPersonalPlaces();
  })
  .then((personal) => {
    state.personal = personal;
    init();
  })
  .catch((err) => {
    // The old build swallowed this with a bare .catch(() => ...), which made
    // every field failure undiagnosable.
    console.error('Trip data could not be loaded:', err);
    showFatal(err);
  });
}

/* Personal places. A missing file, a malformed file, a wrong version or a
 * stalled request all yield an empty list and ONE console warning. None of
 * them may break the page: the file is optional by design, and the 406
 * tracker places must render whether or not it exists. */
function loadPersonalPlaces() {
  const request = fetch('data/my-places.json?v=5')
    .then((r) => {
      // 404 is the normal state before the first personal place is added, but
      // it is still reported once, so a file that fails to publish is visible
      // rather than looking like "no personal places yet".
      if (r.status === 404) {
        throw new Error('data/my-places.json is not published (HTTP 404)');
      }
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return r.json();
    })
    .then((doc) => {
      if (doc.version !== 1) {
        throw new Error(`unexpected version ${JSON.stringify(doc.version)}`);
      }
      if (!Array.isArray(doc.places)) throw new Error('"places" is not an array');
      return doc.places
        .filter((p) => p && typeof p === 'object' && p.name)
        // origin is forced here rather than trusted from the file, so a row
        // can never render without its MY PICK marking.
        .map((p) => Object.assign({}, p, { origin: 'personal' }));
    })
    .catch((err) => {
      console.warn(
        'Personal places could not be loaded; continuing with tracker places only:',
        err
      );
      return [];
    });

  const deadline = new Promise((resolve) => {
    setTimeout(() => resolve(null), PERSONAL_TIMEOUT_MS);
  });

  return Promise.race([request, deadline]).then((rows) => rows || []);
}

function showFatal(err) {
  const main = $('main');
  if (!main) return;
  main.innerHTML =
    '<section class="section"><h1>Could not load the trip data.</h1>' +
    '<p>Try refreshing. If it keeps happening, check that ' +
    '<code>data/trip-data.json</code> is published alongside this page.</p>' +
    `<p class="fatal-detail">${esc(err && err.message ? err.message : String(err))}</p>` +
    '</section>';
}

/* Each render step is isolated. The old build ran them as one chain of
 * statements, so a throw inside the map killed Explore and Schedule too. */
function step(label, fn) {
  try {
    fn();
  } catch (err) {
    console.error(`Render step "${label}" failed:`, err);
  }
}

function init() {
  step('stats', renderStats);
  step('filters', fillFilters);
  step('charts', drawVisuals);
  step('map', initMap);
  step('routeStrip', renderRoute);
  step('places', renderPlaces);
  step('itinerary', renderItinerary);
  step('listeners', bindListeners);
  // Last, so a bad hash in a bookmark cannot stop the rest of the page from
  // rendering behind it.
  step('cityRoute', routeFromHash);
}

/* --------------------------------------------------------------- stats ---- */

function renderStats() {
  const m = state.meta;
  $('#placeCount').textContent = m.places ?? state.places.length;
  $('#cityCount').textContent = m.cities ?? unique(state.places.map((p) => p.city)).length;
  $('#dayCount').textContent = m.days ?? state.itinerary.length;
  $('#mustCount').textContent =
    m.musts ?? state.places.filter((p) => p.priority === 'Must').length;
  $('#statGrid').setAttribute('aria-busy', 'false');

  // Personal places are reported alongside the tracker total, never added to
  // it. meta is not mutated: the four figures above stay 406 / 27 / 76 / 149
  // whatever is in data/my-places.json.
  const note = $('#personalNote');
  if (note) {
    const n = state.personal.length;
    if (n) {
      note.textContent = `Plus ${n} personal pick${n === 1 ? '' : 's'} you added.`;
      note.hidden = false;
    } else {
      note.textContent = '';
      note.hidden = true;
    }
  }

  if (m.generatedAt) {
    $('#dataStamp').textContent = `Data generated ${m.generatedAt.replace('T', ' ').replace('+00:00', ' UTC')}.`;
  }
  renderNextStop();
}

function renderNextStop() {
  const today = startOfDay(new Date());
  const rows = state.itinerary.filter((r) => parseDate(r.date));
  if (!rows.length) return;

  const first = parseDate(rows[0].date);
  const last = parseDate(rows[rows.length - 1].date);
  let label = 'Next stop';
  let row = null;

  if (today < first) {
    label = 'First stop';
    row = rows[0];
  } else if (today > last) {
    label = 'Trip complete';
    row = rows[rows.length - 1];
  } else {
    label = 'Today';
    row = rows.find((r) => sameDay(parseDate(r.date), today)) || rows[0];
  }

  $('#nextStopLabel').textContent = label;
  const city = row.baseCity || row.base;
  const shown = row.country ? `${city}, ${row.country}` : city;

  // "The city I am in" is the one place this feature is most wanted from, so
  // it is a link when there is anything to show. Transit days, which have no
  // saved places, stay as plain text rather than offering an empty page.
  const saved = allPlaces().filter((p) => p.city === city).length;
  $('#nextStopCity').innerHTML = saved
    ? `<a href="#city/${esc(citySlug(city))}">${esc(shown)}</a>`
    : esc(shown);

  const d = parseDate(row.date);
  $('#nextStopDate').innerHTML = d
    ? `${d.toLocaleDateString('en-GB', { month: 'short' }).toUpperCase()}<br />${d.getDate()}`
    : '—';
}

/* ------------------------------------------------------------- filters ---- */

function fillFilters() {
  // Built from the merged list, so a personal place with a type or city that
  // no tracker place uses is still reachable from the filters.
  const all = allPlaces();
  fillSelect('cityFilter', unique(all.map((p) => p.city)).sort());
  fillSelect('typeFilter', unique(all.map((p) => p.type)).sort());
  fillSelect('priorityFilter', ['Must', 'Nice', 'If nearby']);
  fillSelect('timeFilter', unique(all.map((p) => p.timeBucket)).sort());
  fillSelect('costFilter', unique(all.map((p) => p.costTier)).sort());
  // The schedule is tracker-only: personal places never enter the itinerary.
  fillSelect('scheduleCity', unique(state.itinerary.map((r) => r.baseCity)));
}

function fillSelect(id, items) {
  const el = $('#' + id);
  if (!el) return;
  items.forEach((x) => {
    el.insertAdjacentHTML('beforeend', `<option value="${esc(x)}">${esc(x)}</option>`);
  });
}

/* -------------------------------------------------------------- charts ---- */

function drawVisuals() {
  const places = state.places;
  const typeChart = $('#typeChart');
  const topCities = $('#topCities');
  const legend = $('#priorityLegend');
  const donut = $('#priorityChart');

  // The old build read topTypes[0][1] unguarded and threw on empty data,
  // which killed every render step after it.
  if (!places.length) {
    typeChart.innerHTML = '<p class="empty">No places to chart.</p>';
    topCities.innerHTML = '';
    legend.innerHTML = '';
    return;
  }

  const types = Object.entries(countBy(places, 'type')).sort((a, b) => b[1] - a[1]).slice(0, 8);
  const max = types[0][1] || 1;
  typeChart.innerHTML = types
    .map(
      ([name, count]) =>
        `<div class="bar-row"><span>${esc(name)}</span>` +
        `<div class="bar-track"><div class="bar-fill" style="width:${(count / max) * 100}%"></div></div>` +
        `<span class="bar-count">${count}</span></div>`
    )
    .join('');

  const cities = Object.entries(countBy(places, 'city')).sort((a, b) => b[1] - a[1]).slice(0, 5);
  topCities.innerHTML = cities
    .map(([city, count]) => `<li>${esc(city)} <b>${count} places</b></li>`)
    .join('');

  // Build the donut from whatever priorities actually exist, so an unexpected
  // value shows up as a grey wedge instead of silently leaving a gap.
  const counts = countBy(places, 'priority');
  const total = places.length;
  const keys = Object.keys(counts).sort(
    (a, b) => (PRIORITY_ORDER[a] ?? 9) - (PRIORITY_ORDER[b] ?? 9)
  );
  let at = 0;
  const stops = keys.map((k) => {
    const pct = (counts[k] / total) * 100;
    const part = `${PRIORITY_COLOURS[k] || FALLBACK_COLOUR} ${at}% ${at + pct}%`;
    at += pct;
    return part;
  });
  donut.style.background = `conic-gradient(${stops.join(',')})`;
  donut.setAttribute(
    'aria-label',
    'Priority split: ' + keys.map((k) => `${counts[k]} ${k}`).join(', ')
  );
  legend.innerHTML = keys
    .map(
      (k) =>
        `<p><span><i class="priority-key" style="background:${PRIORITY_COLOURS[k] || FALLBACK_COLOUR}"></i>${esc(k)}</span><b>${counts[k]}</b></p>`
    )
    .join('');
}

function countBy(arr, key) {
  return arr.reduce((acc, x) => {
    const k = x[key] || 'Other';
    acc[k] = (acc[k] || 0) + 1;
    return acc;
  }, {});
}

/* ----------------------------------------------------------------- map ---- */

function initMap() {
  const el = $('#map');
  if (!window.L) {
    el.innerHTML =
      '<p class="empty">The map library did not load. Everything else on this page still works.</p>';
    return;
  }

  const legs = state.route.filter((r) => Number.isFinite(r.lat) && Number.isFinite(r.lon));
  if (!legs.length) {
    el.innerHTML = '<p class="empty">No mappable stops in the trip data.</p>';
    return;
  }

  const map = L.map('map', { scrollWheelZoom: false, zoomControl: false }).setView([49.5, 10], 4);
  state.map = map;
  L.control.zoom({ position: 'bottomright' }).addTo(map);
  L.tileLayer(TILES.url, TILES.options).addTo(map);

  // Ordered legs, not a globally de-duplicated set. This is what makes both
  // Cologne blocks appear; the old code drew Cologne once and skipped the
  // Prague -> Cologne -> Copenhagen leg entirely.
  const line = legs.map((r) => [r.lat, r.lon]);
  L.polyline(line, { color: '#17332e', weight: 2, dashArray: '5 7', opacity: 0.8 }).addTo(map);

  const seen = new Set();
  legs.forEach((leg) => {
    const count = state.places.filter((p) => p.city === leg.city).length;
    const mine = state.personal.filter((p) => p.city === leg.city).length;
    const nights = state.route
      .filter((r) => r.city === leg.city)
      .reduce((sum, r) => sum + r.nights, 0);
    const visits = state.route.filter((r) => r.city === leg.city).length;
    const marker = L.marker([leg.lat, leg.lon], {
      icon: L.divIcon({ className: 'city-marker', iconSize: [13, 13] }),
      title: leg.city,
    })
      .addTo(map)
      .bindPopup(
        `<strong>${esc(leg.city)}</strong><br>${nights} night${nights === 1 ? '' : 's'}` +
          (visits > 1 ? ` across ${visits} stays` : '') +
          `<br>${count || 'No'} saved place${count === 1 ? '' : 's'}` +
          (mine ? ` <br>★ ${mine} of your own` : '') +
          // A plain hash link, so the popup keeps working if a click handler
          // ever throws, and the target can be opened in a new tab.
          (count
            ? `<br><a class="popup-link" href="#city/${esc(citySlug(leg.city))}">Open the city page</a>`
            : '')
      );
    if (!seen.has(leg.city)) {
      state.markers[leg.city] = marker;
      seen.add(leg.city);
    }
  });

  // Day stops: passed through, never slept in. The old build had places for
  // Córdoba, Setenil and Peñíscola but no way to see them on the map.
  const dayStops = [];
  state.itinerary.forEach((r) => (r.stops || []).forEach((s) => dayStops.push(s)));
  dayStops.forEach((s) => {
    const saved = allPlaces().filter((p) => p.city === s.name).length;
    L.marker([s.lat, s.lon], {
      icon: L.divIcon({ className: 'stop-marker', iconSize: [10, 10] }),
      title: s.name,
    })
      .addTo(map)
      .bindPopup(
        `<strong>${esc(s.name)}</strong><br>Day stop, no overnight` +
        (saved
          ? `<br><a class="popup-link" href="#city/${esc(citySlug(s.name))}">Open the city page</a>`
          : '')
      );
  });

  // Branch A spur to Dortmund for the Champions League match.
  state.itinerary
    .filter((r) => r.kind === 'branch')
    .forEach((r) => {
      const a = (r.branches || []).find((b) => b.id === 'A');
      const b = (r.branches || []).find((x) => x.id === 'B');
      if (!a || !b) return;
      L.polyline([[b.lat, b.lon], [a.lat, a.lon]], {
        color: '#b03214', weight: 2, dashArray: '2 6', opacity: 0.9,
      }).addTo(map);
      L.marker([a.lat, a.lon], {
        icon: L.divIcon({ className: 'branch-marker', iconSize: [11, 11] }),
        title: a.city + ' (branch A)',
      })
        .addTo(map)
        .bindPopup(`<strong>${esc(a.city)}</strong><br>Branch A only, 9 Dec`);
    });

  // fitBounds throws "Bounds are not valid." on an empty array.
  if (line.length) map.fitBounds(line, { padding: [40, 40], maxZoom: 6 });

  const legend = $('#routeLegend');
  if (legend) {
    legend.textContent =
      `${legs.length} legs · ${unique(legs.map((l) => l.city)).length} cities · ` +
      `${dayStops.length} day stops · dashed red line is the 9 Dec branch A spur to Dortmund`;
  }
}

/* --------------------------------------------------------- route strip ---- */

function renderRoute() {
  const cities = unique(state.route.map((r) => r.city));
  $('#routeStrip').innerHTML = cities
    .map(
      (c) =>
        `<button class="route-city" type="button" aria-pressed="false" data-city="${esc(c)}">${esc(c)}</button>`
    )
    .join('');
  // Selecting a city now opens that city's page rather than only filtering
  // Explore. The filter is still one click away, from the button at the top of
  // the city page.
  document.querySelectorAll('.route-city').forEach((btn) => {
    btn.addEventListener('click', () => openCity(btn.dataset.city));
  });
}

function selectCity(city) {
  const filter = $('#cityFilter');
  if ([...filter.options].some((o) => o.value === city)) filter.value = city;
  state.visibleCount = PAGE_SIZE;
  renderPlaces();

  document.querySelectorAll('.route-city').forEach((btn) => {
    const on = btn.dataset.city === city;
    btn.classList.toggle('active', on);
    btn.setAttribute('aria-pressed', String(on));
  });

  const marker = state.markers[city];
  if (state.map && marker) {
    state.map.flyTo(marker.getLatLng(), 6);
    marker.openPopup();
  }
  $('#explore').scrollIntoView({ behavior: 'smooth' });
}

/* ----------------------------------------------------------- city view ---- */

/* A per-city page reached at #city/<slug>.
 *
 * The neighbourhood list is the primary content and the map is secondary.
 * That order is forced by the data, not by preference. scripts/audit_places.py
 * measured 75 of 406 places with a real position, all of them in Amsterdam,
 * Ghent and Luxembourg City; the other 24 cities have none. A map-first city
 * page would therefore be empty for almost every city on the trip. Areas, by
 * contrast, are recorded on 399 of 406 places.
 *
 * A city centroid is never drawn as if it were the place. Places without a
 * real position are listed, left off the map, and the shortfall is stated in
 * words. As coordinates get filled in the master file, places move from the
 * list to the map on their own.
 */

// The same rule as COORD_PAIR in scripts/coords.py: both halves need a decimal
// point and at least three decimals, so street numbers, postcodes and price
// ranges cannot match. Deliberately written without a lookbehind. An
// unsupported (?<!...) is a parse-time SyntaxError, which would take this whole
// file down on an older browser instead of failing one function.
const COORD_PAIR = /(^|[^\d.])(-?\d{1,3}\.\d{3,})\s*,\s*(-?\d{1,3}\.\d{3,})(?![\d.])/;

const CITY_ROUTE = /^#city\/(.+)$/;

const foldText = (s) =>
  String(s == null ? '' : s).normalize('NFD').replace(/[\u0300-\u036f]/g, '');

// Matches slugify() in scripts/coords.py for every name in city_reference.json,
// which is asserted in the test suite rather than assumed.
const slugify = (s) =>
  foldText(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

function inRange(lat, lon) {
  return (
    Number.isFinite(lat) && Number.isFinite(lon) &&
    lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180
  );
}

/* Resolve one place to a plottable position, or null.
 *
 * Reads both data shapes. After the next extractor run every place carries
 * lat/lon/coordSource/coordPrecision; the committed data/trip-data.json is
 * still the pre-M2 file, where the same pairs sit as text in the tracker's own
 * "address or coordinates" column. Both are handled, so the feature works
 * before and after that run.
 *
 * A city centroid is rejected on either field, so losing one of them in a
 * hand-edited row still cannot promote an inferred point to a real one.
 */
function exactCoords(p) {
  if (p.coordSource === 'cityCentroid' || p.coordPrecision === 'approx') return null;
  if (inRange(p.lat, p.lon)) return { lat: p.lat, lon: p.lon };
  const m = COORD_PAIR.exec(String(p['address or coordinates'] || ''));
  if (!m) return null;
  const lat = parseFloat(m[2]);
  const lon = parseFloat(m[3]);
  return inRange(lat, lon) ? { lat, lon } : null;
}

function citySlug(name) {
  const row = state.cities[name];
  return (row && row.slug) || slugify(name);
}

function cityFromSlug(slug) {
  const want = String(slug || '').toLowerCase();
  const names = unique(
    Object.keys(state.cities).concat(allPlaces().map((p) => p.city))
  );
  return names.find((n) => citySlug(n) === want) || null;
}

/* Group a city's places into areas.
 *
 * Day trips come out first and are counted separately. Every one of the seven
 * places with a blank neighbourhood is a day trip (Bruges, Antwerp, Brussels,
 * Utrecht, Haarlem, Rotterdam, Zaanse Schans), so pulling day trips out also
 * empties the "area not recorded" bucket. It is still built, because the next
 * data refresh could add a blank that is not a day trip.
 */
function cityGroups(city) {
  const rows = allPlaces().filter((p) => p.city === city);
  const trips = rows.filter((p) => p.type === 'day trip');
  const inTown = rows.filter((p) => p.type !== 'day trip');

  const byArea = new Map();
  inTown.forEach((p) => {
    const key = String(p.neighbourhood || '').trim() || 'Area not recorded';
    if (!byArea.has(key)) byArea.set(key, []);
    byArea.get(key).push(p);
  });

  const areas = [...byArea.entries()]
    .map(([name, places]) => ({
      name,
      places,
      must: places.filter((p) => p.priority === 'Must').length,
      mapped: places.filter((p) => exactCoords(p)).length,
    }))
    .sort((a, b) =>
      b.places.length - a.places.length ||
      b.must - a.must ||
      a.name.localeCompare(b.name)
    );

  return {
    rows,
    trips,
    // 132 of the 208 (city, area) pairs hold exactly one place. Left inline
    // they bury the areas that actually cluster, so they collapse into one
    // group at the bottom.
    areas: areas.filter((a) => a.places.length > 1),
    singles: areas.filter((a) => a.places.length === 1),
  };
}

function openCity(city) {
  const slug = citySlug(city);
  if (location.hash === '#city/' + slug) renderCityView(city);
  else location.hash = '#city/' + slug;
}

function closeCityView() {
  document.body.classList.remove('city-open');
  const section = $('#cityView');
  if (section) section.hidden = true;
  if (state.cityMap) {
    state.cityMap.remove();
    state.cityMap = null;
  }
  state.cityName = null;
}

/* Called on load and on every hash change. Anything that is not a #city/<slug>
 * route closes the view and lets the normal in-page anchors work. */
function routeFromHash() {
  const match = CITY_ROUTE.exec(location.hash || '');
  if (!match) {
    closeCityView();
    return;
  }
  let slug;
  try {
    slug = decodeURIComponent(match[1]);
  } catch (err) {
    slug = match[1];
  }
  const city = cityFromSlug(slug);
  if (!city) {
    // A stale bookmark should say so rather than silently showing the homepage.
    renderCityMissing(slug);
    return;
  }
  renderCityView(city);
}

function renderCityMissing(slug) {
  const section = $('#cityView');
  if (!section) return;
  document.body.classList.add('city-open');
  section.hidden = false;
  $('#cityViewHeading').textContent = 'No such city';
  $('#citySub').textContent =
    `Nothing in this trip has the address "${slug}". The city may have been ` +
    'renamed in the master file.';
  $('#cityCoverage').textContent = '';
  $('#cityAreas').innerHTML = '';
  $('#cityDayTrips').innerHTML = '';
  $('#cityMapWrap').hidden = true;
  $('#cityToExplore').hidden = true;
  window.scrollTo(0, 0);
}

function renderCityView(city) {
  const section = $('#cityView');
  if (!section) return;

  state.cityName = city;
  document.body.classList.add('city-open');
  section.hidden = false;
  $('#cityToExplore').hidden = false;

  const groups = cityGroups(city);
  const info = state.cities[city] || {};
  const stays = state.route.filter((r) => r.city === city);
  const nights = stays.reduce((sum, r) => sum + (r.nights || 0), 0);
  const mine = groups.rows.filter((p) => p.origin === 'personal').length;

  $('#cityViewHeading').textContent = city;

  const bits = [];
  if (info.country) bits.push(info.country);
  if (nights) {
    bits.push(
      `${nights} night${nights === 1 ? '' : 's'}` +
      (stays.length > 1 ? ` across ${stays.length} stays` : '')
    );
  }
  bits.push(`${groups.rows.length} saved place${groups.rows.length === 1 ? '' : 's'}`);
  if (mine) bits.push(`★ ${mine} of your own`);
  $('#citySub').textContent = bits.join(' · ');

  $('#cityToExplore').textContent = `Show all ${groups.rows.length} in Explore`;

  // The whole list is built before the map is touched, so a Leaflet failure
  // cannot cost the part of the page that carries the actual content.
  renderCityAreas(groups);
  renderCityTrips(city, groups);
  renderCityCoverage(groups);
  step('cityMap', () => renderCityMap(city, groups));

  window.scrollTo(0, 0);
  $('#cityViewHeading').focus();
}

function renderCityCoverage(groups) {
  const total = groups.rows.length;
  const mapped = groups.rows.filter((p) => exactCoords(p)).length;
  const el = $('#cityCoverage');
  if (!el) return;

  el.textContent = mapped
    ? `${mapped} of ${total} place${total === 1 ? '' : 's'} ` +
      `${mapped === 1 ? 'has' : 'have'} a recorded location. ` +
      `The other ${total - mapped} are listed here but not on the map.`
    : 'None of these places has a recorded location yet, so the map is empty. ' +
      'Fill the coordinates with scripts/coord_worksheet.py and they appear here.';
  el.classList.toggle('is-empty', mapped === 0);
}

function renderCityAreas(groups) {
  const host = $('#cityAreas');
  if (!host) return;

  if (!groups.areas.length && !groups.singles.length) {
    host.innerHTML =
      '<p class="empty">No in-town places saved for this city yet.</p>';
    return;
  }

  // The densest area opens by default; everything below it starts closed so the
  // shape of the city is readable in one screen.
  const blocks = groups.areas.map((a, i) => areaBlock(a, i === 0));

  if (groups.singles.length) {
    const rows = groups.singles
      .map(
        (a) =>
          `<li class="single-area"><b>${esc(a.name)}</b>${placeRow(a.places[0])}</li>`
      )
      .join('');
    blocks.push(
      '<details class="area area-singles">' +
      '<summary><span class="area-name">' +
      `${groups.singles.length} other area${groups.singles.length === 1 ? '' : 's'}` +
      '</span>' +
      `<span class="area-count">${groups.singles.length} place${groups.singles.length === 1 ? '' : 's'}</span>` +
      `</summary><ul class="area-places">${rows}</ul></details>`
    );
  }

  host.innerHTML = `<h3 class="city-subhead">Areas</h3>${blocks.join('')}`;
}

function areaBlock(a, open) {
  const counts = [`${a.places.length} places`];
  if (a.must) counts.push(`${a.must} must`);
  return (
    `<details class="area"${open ? ' open' : ''}>` +
    `<summary><span class="area-name">${esc(a.name)}</span>` +
    `<span class="area-count">${esc(counts.join(' · '))}</span></summary>` +
    `<ul class="area-places">${a.places.map((p) => `<li>${placeRow(p)}</li>`).join('')}</ul>` +
    '</details>'
  );
}

function renderCityTrips(city, groups) {
  const host = $('#cityDayTrips');
  if (!host) return;
  if (!groups.trips.length) {
    host.innerHTML = '';
    return;
  }

  // Out-of-town by definition: every place further than 5 km from its city
  // centroid is typed "day trip" in this data. They are kept out of the map
  // bounds below, because Rotterdam at 57 km would zoom Amsterdam to
  // uselessness.
  const n = groups.trips.length;
  host.innerHTML =
    '<details class="area area-trips">' +
    `<summary><span class="area-name">${n} trip${n === 1 ? '' : 's'} out of ${esc(city)}</span>` +
    '<span class="area-count">not in town</span></summary>' +
    `<ul class="area-places">${groups.trips.map((p) => `<li>${placeRow(p)}</li>`).join('')}</ul>` +
    '</details>';
}

function placeRow(p) {
  const mine = p.origin === 'personal';
  const priority = p.priority || 'Nice';
  const maps = p['maps link'];
  // Only a real http(s) link is rendered. 154 of the 406 maps link values are
  // not usable URLs: 46 are the bare word "maps", 12 are empty and 95 have no
  // scheme, and those rendered as broken links on the old place cards.
  const href = /^https?:\/\//i.test(String(maps || '')) ? maps : '';

  return (
    `<div class="city-place${mine ? ' is-mine' : ''}">` +
    '<div class="city-place-top">' +
    `<span class="city-place-name">${mine ? '<span class="mine-chip">★ MY PICK</span> ' : ''}${esc(p.name)}</span>` +
    `<span class="priority ${priority === 'Must' ? 'must' : ''}">${esc(priority)}</span>` +
    '</div>' +
    `<p class="city-place-why">${esc(p['why it made the list'] || 'Saved for this trip.')}</p>` +
    '<p class="city-place-meta">' +
    `<span class="tag">${esc(p.type)}</span>` +
    (p['opening hours'] ? ` · ${esc(p['opening hours'])}` : '') +
    (exactCoords(p) ? '' : ' · <span class="no-fix">no location recorded</span>') +
    (href
      ? ` · <a href="${esc(href)}" target="_blank" rel="noopener noreferrer">Open map<span class="sr-only"> (opens in a new tab)</span></a>`
      : '') +
    '</p></div>'
  );
}

function renderCityMap(city, groups) {
  const wrap = $('#cityMapWrap');
  const el = $('#cityMap');
  const note = $('#cityMapNote');
  if (!wrap || !el) return;
  wrap.hidden = false;

  if (state.cityMap) {
    state.cityMap.remove();
    state.cityMap = null;
  }
  el.innerHTML = '';

  const inTown = [];
  const trips = [];
  groups.rows.forEach((p) => {
    const c = exactCoords(p);
    if (!c) return;
    (p.type === 'day trip' ? trips : inTown).push({ place: p, coords: c });
  });

  if (!inTown.length && !trips.length) {
    // Not an error state, and not dressed up as one. Most cities are here.
    el.innerHTML =
      '<p class="empty">Nothing to plot yet. Every place in ' +
      `${esc(city)} is in the list, none has coordinates.</p>`;
    if (note) note.hidden = true;
    return;
  }

  if (!window.L) {
    el.innerHTML =
      '<p class="empty">The map library did not load. The areas and places ' +
      'on the left are unaffected.</p>';
    if (note) note.hidden = true;
    return;
  }

  const map = L.map(el, { scrollWheelZoom: false, zoomControl: false });
  state.cityMap = map;
  L.control.zoom({ position: 'bottomright' }).addTo(map);
  L.tileLayer(TILES.url, TILES.options).addTo(map);

  const add = (entry, className) => {
    const { place, coords } = entry;
    L.marker([coords.lat, coords.lon], {
      icon: L.divIcon({ className, iconSize: [12, 12] }),
      title: place.name,
    })
      .addTo(map)
      .bindPopup(
        `<strong>${esc(place.name)}</strong><br>${esc(place.neighbourhood || place.type)}` +
        `<br>${esc(place.priority || 'Nice')}`
      );
  };
  inTown.forEach((e) => add(e, 'place-marker'));
  trips.forEach((e) => add(e, 'trip-marker'));

  // Bounds come from the in-town places only. Day trips are still drawn, so
  // they can be found by zooming out, but they never set the frame.
  const frame = (inTown.length ? inTown : trips).map((e) => [e.coords.lat, e.coords.lon]);
  map.fitBounds(frame, { padding: [30, 30], maxZoom: 15 });

  if (note) {
    note.hidden = false;
    note.textContent =
      `${inTown.length} in town` +
      (trips.length ? ` · ${trips.length} out of town, outside the frame` : '');
  }
  // The map was built inside a hidden section on first paint.
  setTimeout(() => map.invalidateSize(), 0);
}

/* -------------------------------------------------------------- places ---- */

function filteredPlaces() {
  const q = $('#searchInput').value.trim().toLowerCase();
  const city = $('#cityFilter').value;
  const type = $('#typeFilter').value;
  const priority = $('#priorityFilter').value;
  const time = $('#timeFilter').value;
  const cost = $('#costFilter').value;
  const sort = $('#sortSelect').value;
  const originEl = $('#originFilter');
  const origin = originEl ? originEl.value : 'all';

  const result = allPlaces().filter((p) => {
    if (q) {
      // SEARCH_FIELDS still excludes the maps link, which is what made "com"
      // and "https" match every row in the original build.
      const hay = SEARCH_FIELDS.map((f) => p[f] || '').join(' ').toLowerCase();
      if (!hay.includes(q)) return false;
    }
    if (origin === 'personal' && p.origin !== 'personal') return false;
    if (origin === 'tracker' && p.origin === 'personal') return false;
    if (city !== 'all' && p.city !== city) return false;
    if (type !== 'all' && p.type !== type) return false;
    if (priority !== 'all' && p.priority !== priority) return false;
    if (time !== 'all' && p.timeBucket !== time) return false;
    if (cost !== 'all' && p.costTier !== cost) return false;
    return true;
  });

  return result.sort((a, b) => {
    if (sort === 'priority') {
      return (
        (PRIORITY_ORDER[a.priority] ?? 9) - (PRIORITY_ORDER[b.priority] ?? 9) ||
        a.city.localeCompare(b.city) ||
        a.name.localeCompare(b.name)
      );
    }
    return String(a[sort] || '').localeCompare(String(b[sort] || ''));
  });
}

function renderPlaces() {
  const result = filteredPlaces();
  const slice = result.slice(0, state.visibleCount);

  $('#resultCount').textContent =
    `${result.length} ${result.length === 1 ? 'place' : 'places'} found` +
    (result.length > slice.length ? ` · showing ${slice.length}` : '');

  $('#placeGrid').innerHTML = slice.length
    ? slice.map(placeCard).join('')
    : '<p class="empty">Nothing matches those filters. Try widening the search.</p>';

  $('#showMore').style.display = result.length > state.visibleCount ? 'block' : 'none';
}

function placeCard(p) {
  const priority = p.priority || 'Nice';
  const maps = p['maps link'];
  const hours = p['opening hours'];
  const confidence = p.confidence;

  // Fields the old build dropped entirely: opening hours, notes, confidence,
  // source and date, address. They are the ones that answer "is it open".
  const mine = p.origin === 'personal';

  const meta = [];
  if (hours) meta.push(`<span class="meta-hours"><b>Hours</b> ${esc(hours)}</span>`);
  if (p.notes) meta.push(`<span class="meta-note"><b>Note</b> ${esc(p.notes)}</span>`);
  // Never present an inferred position as an exact one.
  if (mine && p.coordPrecision === 'approx') {
    meta.push(
      '<span class="meta-approx"><b>Location</b> approximate, city centre ' +
      'until a map link or coordinates are added</span>'
    );
  }

  return (
    `<article class="place-card${mine ? ' is-mine' : ''}">` +
    '<div class="place-top"><span class="tag">' +
    // Glyph plus colour, not colour alone, matching the HEAVY DAY treatment.
    (mine ? '<span class="mine-chip">★ MY PICK</span> ' : '') +
    `${esc(p.type)}</span>` +
    `<span class="priority ${priority === 'Must' ? 'must' : ''}">${esc(priority)}</span></div>` +
    `<h3>${esc(p.name)}</h3>` +
    `<p class="place-city">${esc(p.city)} · ${esc(p.neighbourhood || 'City centre')}</p>` +
    `<p class="why">${esc(p['why it made the list'] || 'Saved for this trip.')}</p>` +
    (meta.length ? `<div class="place-meta">${meta.join('')}</div>` : '') +
    '<div class="place-bottom">' +
    `<span>${esc(p['best time'] || 'Flexible')} · ${esc(p['approx cost'] || 'Price TBC')}` +
    (confidence && confidence !== 'Verified'
      ? ` · <em class="confidence">${esc(confidence)}</em>`
      : '') +
    '</span>' +
    (maps
      ? `<a href="${esc(maps)}" target="_blank" rel="noopener noreferrer">Open map <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a>`
      : '') +
    '</div></article>'
  );
}

/* ----------------------------------------------------------- itinerary ---- */

function renderItinerary() {
  const city = $('#scheduleCity').value;
  const rows = state.itinerary.filter((r) => {
    if (city !== 'all' && r.baseCity !== city) return false;
    if (state.heavyOnly && !r.heavy) return false;
    return true;
  });

  const heavyTotal = state.itinerary.filter((r) => r.heavy).length;
  $('#scheduleStatus').textContent =
    `Showing ${rows.length} of ${state.itinerary.length} days` +
    (state.heavyOnly ? ` · ${heavyTotal} heavy days in the whole trip` : '');

  $('#itineraryList').innerHTML = rows.length
    ? rows.map(dayRow).join('')
    : '<p class="empty">No days match.</p>';
}

function dayRow(r) {
  const d = parseDate(r.date);
  const dateLabel = d
    ? d.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' })
    : esc(r.date || 'Undated');

  const today = startOfDay(new Date());
  const isToday = d && sameDay(d, today);

  const cityLabel = r.baseCity || r.base;
  const stops = (r.stops || []).map((s) => s.name);

  const branchHtml = (r.branches || [])
    .map(
      (b) =>
        `<p class="branch"><b>Branch ${esc(b.id)} — ${esc(b.city)}</b> ${esc(b.notes)}</p>`
    )
    .join('');

  return (
    `<article class="day-row${r.heavy ? ' is-heavy' : ''}${isToday ? ' is-today' : ''}" id="day-${esc(r.date)}">` +
    `<time class="day-date" datetime="${esc(r.date)}">${esc(dateLabel)}</time>` +
    `<div class="day-city">${esc(cityLabel)}<small>${esc(r.country || kindLabel(r.kind))}</small>` +
    (stops.length ? `<small class="via">via ${esc(stops.join(', '))}</small>` : '') +
    '</div>' +
    '<div class="day-notes">' +
    (r.heavy ? '<span class="heavy-flag">◆ HEAVY DAY</span> ' : '') +
    (isToday ? '<span class="today-flag">TODAY</span> ' : '') +
    esc(r.notes || '') +
    branchHtml +
    '</div></article>'
  );
}

function kindLabel(kind) {
  if (kind === 'transit') return 'Overnight train';
  if (kind === 'branch') return 'Branch decision';
  if (kind === 'depart') return 'Departure';
  return '';
}

/* ----------------------------------------------------------- listeners ---- */

function bindListeners() {
  const filterIds = [
    'searchInput', 'cityFilter', 'typeFilter',
    'priorityFilter', 'timeFilter', 'costFilter', 'originFilter', 'sortSelect',
  ];
  filterIds.forEach((id) => {
    const el = $('#' + id);
    if (!el) return;
    el.addEventListener('input', () => {
      state.visibleCount = PAGE_SIZE;
      renderPlaces();
    });
  });

  $('#clearFilters').addEventListener('click', () => {
    [
      'cityFilter', 'typeFilter', 'priorityFilter',
      'timeFilter', 'costFilter', 'originFilter',
    ].forEach((id) => {
      const el = $('#' + id);
      if (el) el.value = 'all';
    });
    $('#searchInput').value = '';
    $('#sortSelect').value = 'priority';
    // The old reset left the route strip highlighted and never touched the
    // schedule filter.
    document.querySelectorAll('.route-city').forEach((btn) => {
      btn.classList.remove('active');
      btn.setAttribute('aria-pressed', 'false');
    });
    state.visibleCount = PAGE_SIZE;
    renderPlaces();
  });

  $('#showMore').addEventListener('click', () => {
    state.visibleCount += PAGE_SIZE;
    renderPlaces();
  });

  $('#scheduleCity').addEventListener('input', renderItinerary);

  $('#heavyToggle').addEventListener('click', (e) => {
    state.heavyOnly = !state.heavyOnly;
    e.currentTarget.setAttribute('aria-pressed', String(state.heavyOnly));
    e.currentTarget.classList.toggle('active', state.heavyOnly);
    renderItinerary();
  });

  // A real "today" control. The old button was called todayButton, labelled
  // "Back to start", and did nothing date-aware.
  $('#todayButton').addEventListener('click', () => {
    $('#scheduleCity').value = 'all';
    state.heavyOnly = false;
    $('#heavyToggle').setAttribute('aria-pressed', 'false');
    $('#heavyToggle').classList.remove('active');
    renderItinerary();

    const today = startOfDay(new Date());
    const match = state.itinerary.find((r) => {
      const d = parseDate(r.date);
      return d && d >= today;
    });
    const target = match ? document.getElementById('day-' + match.date) : null;
    (target || $('#schedule')).scrollIntoView({ behavior: 'smooth', block: 'center' });
  });

  // Bookmarkable and back-button friendly, which is the point on the ground.
  window.addEventListener('hashchange', () => step('cityRoute', routeFromHash));

  $('#cityBack').addEventListener('click', (e) => {
    e.preventDefault();
    // Replacing rather than pushing keeps Back going where the user came from
    // instead of bouncing between the city view and the homepage.
    history.replaceState(null, '', location.pathname + location.search);
    closeCityView();
    $('#route').scrollIntoView();
  });

  $('#cityToExplore').addEventListener('click', () => {
    const city = state.cityName;
    history.replaceState(null, '', location.pathname + location.search);
    closeCityView();
    if (city) selectCity(city);
  });

  const navToggle = $('#navToggle');
  const mobileNav = $('#mobileNav');
  navToggle.addEventListener('click', () => {
    const open = navToggle.getAttribute('aria-expanded') === 'true';
    navToggle.setAttribute('aria-expanded', String(!open));
    mobileNav.hidden = open;
  });
  mobileNav.addEventListener('click', (e) => {
    if (e.target.tagName === 'A') {
      navToggle.setAttribute('aria-expanded', 'false');
      mobileNav.hidden = true;
    }
  });
}

/* ------------------------------------------------------------- helpers ---- */

// Midday avoids the timezone off-by-one. The old build did this too but never
// checked the result, so a bad date rendered the literal text "Invalid Date".
function parseDate(iso) {
  if (!iso || typeof iso !== 'string') return null;
  const d = new Date(iso + 'T12:00:00');
  return Number.isNaN(d.getTime()) ? null : d;
}

function startOfDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate(), 12, 0, 0);
}

function sameDay(a, b) {
  return (
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate()
  );
}

/* ------------------------------------------------------- offline shell ---- */

if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('sw.js')
      .catch((err) => console.warn('Service worker registration failed:', err));
  });
}
